export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_FAILURE = 'GET_ALL_QUESTIONS_FAILURE';

export const GET_SINGLE_QUESTION = 'GET_SINGLE_QUESTION';
export const GET_SINGLE_QUESTION_SUCCESS = 'GET_SINGLE_QUESTION_SUCCESS';
export const GET_SINGLE_QUESTION_FAILURE = 'GET_SINGLE_QUESTION_FAILURE';

export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';


export const DELETE_QUESTION = 'DELETE_QUESTION';

export const ADD_NEW_ANSWER = 'ADD_NEW_ANSWER';

export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';

export const ACCEPT_ANSWER = 'ACCEPT_ANSWER';

export const UPVOTE_ANSWER = 'UPVOTE_ANSWER';
export const DOWNVOTE_ANSWER = 'DOWNVOTE_ANSWER';


export const GET_ALL_REPLIES = 'GET_ALL_REPLIES';
export const GET_ALL_REPLIES_SUCCESS = 'GET_ALL_REPLIES_SUCCESS';
export const GET_ALL_REPLIES_FAILURE = 'GET_ALL_REPLIES_FAILURE';

export const DELETE_REPLY_REQUEST = 'DELETE_REPLY_REQUEST';
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS';
export const DELETE_REPLY_FAILURE = 'DELETE_REPLY_FAILURE';

export const SIGN_USER_UP_SUCCESS = 'SIGN_USER_UP_SUCCESS';
export const SIGN_USER_IN_SUCCESS = 'SIGN_USER_IN_SUCCESS';

export const GET_ANSWERS_REQUEST = 'GET_ANSWERS_REQUEST';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_ANSWERS_FALURE = 'GET_ANSWERS_FAILURE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

export const USER_QUESTIONS_REQUEST = 'USER_QUESTIONS_REQUEST';
export const USER_QUESTIONS_SUCCESS = 'USER_QUESTIONS_SUCCESS';
export const USER_QUESTIONS_FAILURE = 'USER_QUESTIONS_FAILURE';

export const USER_ANSWERS_REQUEST = 'USER_ANSWERS_REQUEST';
export const USER_ANSWERS_SUCCESS = 'USER_ANSWERS_SUCCESS';
export const USER_ANSWERS_FAILURE = 'USER_ANSWERS_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const TOP_QUESTION_REQUEST = 'TOP_QUESTION_REQUEST';
export const TOP_QUESTION_SUCCESS = 'TOP_QUESTION_SUCCESS';
export const TOP_QUESTION_FAILURE = 'TOP_QUESTION_FAILURE';
